# Generated by Django 5.2.6 on 2026-07-18 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cls_id', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.class')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='학생', max_length=50)),
                ('number', models.IntegerField(default=0)),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('has_eaten', models.BooleanField(default=False)),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.class')),
            ],
        ),
    ]
