# Generated by Django 5.2.16 on 2026-07-20 09:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('waiting_count', models.IntegerField(default=0)),
                ('service_time_per_person', models.FloatField(default=3.0)),
                ('expected_wait_seconds', models.FloatField(default=0.0)),
                ('actual_wait_seconds', models.FloatField(blank=True, null=True)),
                ('is_congested', models.BooleanField(default=False)),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.class')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
